"""add automation control plane

Revision ID: 30b5ceab28ca
Revises: e14b778c54af
Create Date: 2026-08-25 09:31:36.416189
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "30b5ceab28ca"
down_revision: str | None = "e14b778c54af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_definitions",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("display_name", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "PAUSED",
                "RETIRED",
                name="workflowstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("active_version", sa.Integer(), nullable=True),
        sa.Column(
            "concurrency_policy",
            sa.Enum(
                "FORBID",
                "ALLOW",
                "REPLACE",
                name="workflowconcurrencypolicy",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("max_concurrency", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("notify_on_success", sa.Boolean(), nullable=False),
        sa.Column("notify_on_failure", sa.Boolean(), nullable=False),
        sa.Column(
            "classification",
            sa.Enum(
                "PUBLIC",
                "INTERNAL",
                "CONFIDENTIAL",
                "RESTRICTED",
                name="classification",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "active_version IS NULL OR active_version > 0",
            name=op.f("ck_workflow_definitions_positive_active_workflow_version"),
        ),
        sa.CheckConstraint(
            "max_concurrency > 0", name=op.f("ck_workflow_definitions_positive_max_concurrency")
        ),
        sa.CheckConstraint(
            "timeout_seconds > 0", name=op.f("ck_workflow_definitions_positive_workflow_timeout")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_workflow_definitions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_workflow_definitions_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workflow_definitions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_definitions")),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "name",
            name=op.f("uq_workflow_definitions_organization_id"),
        ),
    )
    op.create_index(
        op.f("ix_workflow_definitions_organization_id"),
        "workflow_definitions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_definitions_status"), "workflow_definitions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_definitions_workspace_id"),
        "workflow_definitions",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "workflow_versions",
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_workflow_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_workflow_versions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_definitions.id"],
            name=op.f("fk_workflow_versions_workflow_id_workflow_definitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_versions")),
        sa.UniqueConstraint(
            "workflow_id", "version", name=op.f("uq_workflow_versions_workflow_id")
        ),
    )
    op.create_index(
        op.f("ix_workflow_versions_organization_id"),
        "workflow_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_versions_workflow_id"), "workflow_versions", ["workflow_id"], unique=False
    )
    op.execute(
        """
        CREATE FUNCTION obsion_guard_workflow_version_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'immutable workflow version cannot be deleted'
              USING ERRCODE = 'integrity_constraint_violation';
          END IF;
          IF OLD.id IS DISTINCT FROM NEW.id
             OR OLD.organization_id IS DISTINCT FROM NEW.organization_id
             OR OLD.workflow_id IS DISTINCT FROM NEW.workflow_id
             OR OLD.version IS DISTINCT FROM NEW.version
             OR OLD.spec::jsonb IS DISTINCT FROM NEW.spec::jsonb
             OR OLD.checksum_sha256 IS DISTINCT FROM NEW.checksum_sha256
             OR OLD.created_by IS DISTINCT FROM NEW.created_by
             OR OLD.created_at IS DISTINCT FROM NEW.created_at
             OR OLD.published_at IS NOT NULL
             OR NEW.published_at IS NULL THEN
            RAISE EXCEPTION 'immutable workflow version cannot be changed'
              USING ERRCODE = 'integrity_constraint_violation';
          END IF;
          RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_workflow_versions_immutable
        BEFORE UPDATE OR DELETE ON workflow_versions
        FOR EACH ROW EXECUTE FUNCTION obsion_guard_workflow_version_mutation()
        """
    )
    op.create_table(
        "workflow_schedules",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_version_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("cron_expression", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column(
            "misfire_policy",
            sa.Enum(
                "SKIP", "FIRE_ONCE", name="schedulemisfirepolicy", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("misfire_grace_seconds", sa.Integer(), nullable=False),
        sa.Column("input_payload", sa.JSON(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("next_fire_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_fire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "misfire_grace_seconds >= 0",
            name=op.f("ck_workflow_schedules_nonnegative_misfire_grace"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_workflow_schedules_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_workflow_schedules_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_workflow_schedules_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_definitions.id"],
            name=op.f("fk_workflow_schedules_workflow_id_workflow_definitions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"],
            ["workflow_versions.id"],
            name=op.f("fk_workflow_schedules_workflow_version_id_workflow_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workflow_schedules_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_schedules")),
        sa.UniqueConstraint("workflow_id", "name", name=op.f("uq_workflow_schedules_workflow_id")),
    )
    op.create_index(
        op.f("ix_workflow_schedules_enabled"), "workflow_schedules", ["enabled"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_schedules_next_fire_at"),
        "workflow_schedules",
        ["next_fire_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_schedules_organization_id"),
        "workflow_schedules",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_schedules_workflow_id"),
        "workflow_schedules",
        ["workflow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_schedules_workspace_id"),
        "workflow_schedules",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_schedules_due", "workflow_schedules", ["enabled", "next_fire_at"], unique=False
    )
    op.create_table(
        "automation_executions",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_version_id", sa.Uuid(), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=True),
        sa.Column(
            "trigger",
            sa.Enum("MANUAL", "SCHEDULE", name="automationtrigger", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=300), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "WAITING_REVIEW",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                "SKIPPED",
                name="automationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("input_payload", sa.JSON(), nullable=False),
        sa.Column("max_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_duration_seconds > 0",
            name=op.f("ck_automation_executions_positive_automation_duration"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_automation_executions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_automation_executions_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["workflow_schedules.id"],
            name=op.f("fk_automation_executions_schedule_id_workflow_schedules"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_definitions.id"],
            name=op.f("fk_automation_executions_workflow_id_workflow_definitions"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"],
            ["workflow_versions.id"],
            name=op.f("fk_automation_executions_workflow_version_id_workflow_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_automation_executions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_executions")),
        sa.UniqueConstraint(
            "organization_id",
            "idempotency_key",
            name=op.f("uq_automation_executions_organization_id"),
        ),
        sa.UniqueConstraint(
            "schedule_id", "scheduled_for", name=op.f("uq_automation_executions_schedule_id")
        ),
    )
    op.create_index(
        op.f("ix_automation_executions_lease_expires_at"),
        "automation_executions",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_executions_organization_id"),
        "automation_executions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_executions_schedule_id"),
        "automation_executions",
        ["schedule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_executions_status"), "automation_executions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_automation_executions_workflow_id"),
        "automation_executions",
        ["workflow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_executions_workspace_id"),
        "automation_executions",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_automation_executions_claim",
        "automation_executions",
        ["status", "lease_expires_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "automation_step_executions",
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column("step_key", sa.String(length=100), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "step_type",
            sa.Enum(
                "ANALYSIS",
                "HUMAN_REVIEW",
                "NOTIFICATION",
                name="workflowsteptype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("depends_on", sa.JSON(), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "WAITING_REVIEW",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                "SKIPPED",
                name="automationstepstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("output_refs", sa.JSON(), nullable=False),
        sa.Column(
            "review_decision",
            sa.Enum("APPROVE", "REJECT", name="reviewdecision", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("review_reason", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["automation_executions.id"],
            name=op.f("fk_automation_step_executions_execution_id_automation_executions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_automation_step_executions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_automation_step_executions_reviewed_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_automation_step_executions_run_id_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_step_executions")),
        sa.UniqueConstraint(
            "execution_id", "ordinal", name="uq_automation_step_executions_ordinal"
        ),
        sa.UniqueConstraint("execution_id", "step_key", name="uq_automation_step_executions_key"),
    )
    op.create_index(
        op.f("ix_automation_step_executions_execution_id"),
        "automation_step_executions",
        ["execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_step_executions_organization_id"),
        "automation_step_executions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_step_executions_run_id"),
        "automation_step_executions",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_step_executions_status"),
        "automation_step_executions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("execution_id", sa.Uuid(), nullable=True),
        sa.Column("step_execution_id", sa.Uuid(), nullable=True),
        sa.Column("recipient_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DELIVERED", "READ", name="notificationstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=300), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["automation_executions.id"],
            name=op.f("fk_notification_deliveries_execution_id_automation_executions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_notification_deliveries_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
            name=op.f("fk_notification_deliveries_recipient_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["step_execution_id"],
            ["automation_step_executions.id"],
            name=op.f("fk_notification_deliveries_step_execution_id_automation_step_executions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_notification_deliveries_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
        sa.UniqueConstraint(
            "organization_id",
            "idempotency_key",
            name=op.f("uq_notification_deliveries_organization_id"),
        ),
    )
    op.create_index(
        op.f("ix_notification_deliveries_execution_id"),
        "notification_deliveries",
        ["execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_organization_id"),
        "notification_deliveries",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_recipient_id"),
        "notification_deliveries",
        ["recipient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_status"),
        "notification_deliveries",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_workspace_id"),
        "notification_deliveries",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_deliveries_inbox",
        "notification_deliveries",
        ["organization_id", "recipient_id", "status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notification_deliveries_inbox", table_name="notification_deliveries")
    op.drop_index(
        op.f("ix_notification_deliveries_workspace_id"), table_name="notification_deliveries"
    )
    op.drop_index(op.f("ix_notification_deliveries_status"), table_name="notification_deliveries")
    op.drop_index(
        op.f("ix_notification_deliveries_recipient_id"), table_name="notification_deliveries"
    )
    op.drop_index(
        op.f("ix_notification_deliveries_organization_id"), table_name="notification_deliveries"
    )
    op.drop_index(
        op.f("ix_notification_deliveries_execution_id"), table_name="notification_deliveries"
    )
    op.drop_table("notification_deliveries")
    op.drop_index(
        op.f("ix_automation_step_executions_status"), table_name="automation_step_executions"
    )
    op.drop_index(
        op.f("ix_automation_step_executions_run_id"), table_name="automation_step_executions"
    )
    op.drop_index(
        op.f("ix_automation_step_executions_organization_id"),
        table_name="automation_step_executions",
    )
    op.drop_index(
        op.f("ix_automation_step_executions_execution_id"), table_name="automation_step_executions"
    )
    op.drop_table("automation_step_executions")
    op.drop_index("ix_automation_executions_claim", table_name="automation_executions")
    op.drop_index(op.f("ix_automation_executions_workspace_id"), table_name="automation_executions")
    op.drop_index(op.f("ix_automation_executions_workflow_id"), table_name="automation_executions")
    op.drop_index(op.f("ix_automation_executions_status"), table_name="automation_executions")
    op.drop_index(op.f("ix_automation_executions_schedule_id"), table_name="automation_executions")
    op.drop_index(
        op.f("ix_automation_executions_organization_id"), table_name="automation_executions"
    )
    op.drop_index(
        op.f("ix_automation_executions_lease_expires_at"), table_name="automation_executions"
    )
    op.drop_table("automation_executions")
    op.drop_index("ix_workflow_schedules_due", table_name="workflow_schedules")
    op.drop_index(op.f("ix_workflow_schedules_workspace_id"), table_name="workflow_schedules")
    op.drop_index(op.f("ix_workflow_schedules_workflow_id"), table_name="workflow_schedules")
    op.drop_index(op.f("ix_workflow_schedules_organization_id"), table_name="workflow_schedules")
    op.drop_index(op.f("ix_workflow_schedules_next_fire_at"), table_name="workflow_schedules")
    op.drop_index(op.f("ix_workflow_schedules_enabled"), table_name="workflow_schedules")
    op.drop_table("workflow_schedules")
    op.execute("DROP TRIGGER IF EXISTS trg_workflow_versions_immutable ON workflow_versions")
    op.execute("DROP FUNCTION IF EXISTS obsion_guard_workflow_version_mutation()")
    op.drop_index(op.f("ix_workflow_versions_workflow_id"), table_name="workflow_versions")
    op.drop_index(op.f("ix_workflow_versions_organization_id"), table_name="workflow_versions")
    op.drop_table("workflow_versions")
    op.drop_index(op.f("ix_workflow_definitions_workspace_id"), table_name="workflow_definitions")
    op.drop_index(op.f("ix_workflow_definitions_status"), table_name="workflow_definitions")
    op.drop_index(
        op.f("ix_workflow_definitions_organization_id"), table_name="workflow_definitions"
    )
    op.drop_table("workflow_definitions")
    # ### end Alembic commands ###
