"""add governed action control plane

Revision ID: 59b7457d48dc
Revises: 30b5ceab28ca
Create Date: 2026-08-25 10:34:14.300863
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "59b7457d48dc"
down_revision: str | None = "30b5ceab28ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_requests",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "GENERATE_PR",
                "CREATE_TICKET",
                "MODIFY_CONFIG",
                "RESTART_SERVICE",
                "DEPLOY",
                name="actiontype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("environment", sa.String(length=80), nullable=False),
        sa.Column("target", sa.JSON(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("rollback_parameters", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PREFLIGHT_FAILED",
                "WAITING_APPROVAL",
                "APPROVED",
                "EXECUTING",
                "COMPLETED",
                "FAILED",
                "WAITING_ROLLBACK_APPROVAL",
                "ROLLBACK_APPROVED",
                "ROLLING_BACK",
                "ROLLED_BACK",
                "ROLLBACK_FAILED",
                "ROLLBACK_REJECTED",
                "REJECTED",
                "EXPIRED",
                "CANCELLED",
                name="actionstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=300), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("plan_checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("preflight", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "timeout_seconds > 0", name=op.f("ck_action_requests_positive_action_timeout")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_action_requests_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_action_requests_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_action_requests_requested_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_action_requests_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_requests")),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name="uq_action_requests_idempotency"
        ),
    )
    op.create_index(
        "ix_action_requests_claim",
        "action_requests",
        ["status", "lease_expires_at", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_requests_environment"), "action_requests", ["environment"], unique=False
    )
    op.create_index(
        op.f("ix_action_requests_lease_expires_at"),
        "action_requests",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_requests_organization_id"),
        "action_requests",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_action_requests_status"), "action_requests", ["status"], unique=False)
    op.create_index(
        op.f("ix_action_requests_workspace_id"), "action_requests", ["workspace_id"], unique=False
    )
    op.create_table(
        "action_approvals",
        sa.Column("action_request_id", sa.Uuid(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "EXECUTE", "ROLLBACK", name="actionapprovalpurpose", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("plan_checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "EXPIRED",
                "CANCELLED",
                name="approvalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("approver_constraints", sa.JSON(), nullable=False),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "revision > 0", name=op.f("ck_action_approvals_positive_action_approval_revision")
        ),
        sa.ForeignKeyConstraint(
            ["action_request_id"],
            ["action_requests.id"],
            name=op.f("fk_action_approvals_action_request_id_action_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["users.id"], name=op.f("fk_action_approvals_decided_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_action_approvals_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_action_approvals_requested_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_approvals")),
        sa.UniqueConstraint(
            "action_request_id", "purpose", "revision", name="uq_action_approvals_revision"
        ),
    )
    op.create_index(
        op.f("ix_action_approvals_action_request_id"),
        "action_approvals",
        ["action_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_approvals_organization_id"),
        "action_approvals",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_action_approvals_pending",
        "action_approvals",
        ["status", "expires_at", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_approvals_status"), "action_approvals", ["status"], unique=False
    )
    op.create_table(
        "action_plans",
        sa.Column("action_request_id", sa.Uuid(), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_request_id"],
            ["action_requests.id"],
            name=op.f("fk_action_plans_action_request_id_action_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_action_plans_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_action_plans_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_plans")),
        sa.UniqueConstraint("action_request_id", name="uq_action_plans_request"),
    )
    op.create_index(
        op.f("ix_action_plans_action_request_id"),
        "action_plans",
        ["action_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_plans_organization_id"), "action_plans", ["organization_id"], unique=False
    )
    op.execute(
        """
        CREATE FUNCTION obsion_guard_action_plan_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
          RAISE EXCEPTION 'immutable action plan cannot be changed or deleted'
            USING ERRCODE = 'integrity_constraint_violation';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_action_plans_immutable
        BEFORE UPDATE OR DELETE ON action_plans
        FOR EACH ROW EXECUTE FUNCTION obsion_guard_action_plan_mutation()
        """
    )
    op.create_table(
        "action_attempts",
        sa.Column("action_request_id", sa.Uuid(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "EXECUTE", "ROLLBACK", name="actionapprovalpurpose", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="actionattemptstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("capability_version_id", sa.Uuid(), nullable=False),
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column("approval_id", sa.Uuid(), nullable=False),
        sa.Column("policy_decision_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=360), nullable=False),
        sa.Column("input_payload", sa.JSON(), nullable=False),
        sa.Column("output", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ordinal > 0", name=op.f("ck_action_attempts_positive_action_attempt_ordinal")
        ),
        sa.ForeignKeyConstraint(
            ["action_request_id"],
            ["action_requests.id"],
            name=op.f("fk_action_attempts_action_request_id_action_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["action_approvals.id"],
            name=op.f("fk_action_attempts_approval_id_action_approvals"),
        ),
        sa.ForeignKeyConstraint(
            ["capability_version_id"],
            ["capability_versions.id"],
            name=op.f("fk_action_attempts_capability_version_id_capability_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["connectors.id"],
            name=op.f("fk_action_attempts_connector_id_connectors"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_action_attempts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["policy_decision_id"],
            ["policy_decisions.id"],
            name=op.f("fk_action_attempts_policy_decision_id_policy_decisions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_attempts")),
        sa.UniqueConstraint(
            "action_request_id", "purpose", "ordinal", name="uq_action_attempts_ordinal"
        ),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name="uq_action_attempts_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_action_attempts_action_request_id"),
        "action_attempts",
        ["action_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_attempts_organization_id"),
        "action_attempts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_action_attempts_status"), "action_attempts", ["status"], unique=False)
    op.add_column(
        "notification_deliveries", sa.Column("action_request_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_notification_deliveries_action_request_id"),
        "notification_deliveries",
        ["action_request_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_notification_deliveries_action_request_id_action_requests"),
        "notification_deliveries",
        "action_requests",
        ["action_request_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_notification_deliveries_action_request_id_action_requests"),
        "notification_deliveries",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_notification_deliveries_action_request_id"), table_name="notification_deliveries"
    )
    op.drop_column("notification_deliveries", "action_request_id")
    op.drop_index(op.f("ix_action_attempts_status"), table_name="action_attempts")
    op.drop_index(op.f("ix_action_attempts_organization_id"), table_name="action_attempts")
    op.drop_index(op.f("ix_action_attempts_action_request_id"), table_name="action_attempts")
    op.drop_table("action_attempts")
    op.execute("DROP TRIGGER IF EXISTS trg_action_plans_immutable ON action_plans")
    op.execute("DROP FUNCTION IF EXISTS obsion_guard_action_plan_mutation()")
    op.drop_index(op.f("ix_action_plans_organization_id"), table_name="action_plans")
    op.drop_index(op.f("ix_action_plans_action_request_id"), table_name="action_plans")
    op.drop_table("action_plans")
    op.drop_index(op.f("ix_action_approvals_status"), table_name="action_approvals")
    op.drop_index("ix_action_approvals_pending", table_name="action_approvals")
    op.drop_index(op.f("ix_action_approvals_organization_id"), table_name="action_approvals")
    op.drop_index(op.f("ix_action_approvals_action_request_id"), table_name="action_approvals")
    op.drop_table("action_approvals")
    op.drop_index(op.f("ix_action_requests_workspace_id"), table_name="action_requests")
    op.drop_index(op.f("ix_action_requests_status"), table_name="action_requests")
    op.drop_index(op.f("ix_action_requests_organization_id"), table_name="action_requests")
    op.drop_index(op.f("ix_action_requests_lease_expires_at"), table_name="action_requests")
    op.drop_index(op.f("ix_action_requests_environment"), table_name="action_requests")
    op.drop_index("ix_action_requests_claim", table_name="action_requests")
    op.drop_table("action_requests")
    # ### end Alembic commands ###
